name: Build executable using Nuitka
on: 
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
      
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64' 
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Update pip and wheel 
        run: |
          python -m pip install --upgrade pip wheel
        
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Ensure fuse2 is installed on Linux
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y libfuse2
          
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: totpprint.py
          onefile: true
  
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
#            build/*.app/**/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      
      - name: Display structure of downloaded files
        run: ls -R
    
      - name: Create release from tag 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            ${{ github.workspace }}/artifacts/Windows Build/*.exe
            ${{ github.workspace }}/artifacts/Linux Build/*.bin
#            ${{ github.workspace }}/artifacts/macOS build/*.app/**/*